# Site settings
title: Raniery Ribeiro
person_name: Raniery Ribeiro
email: enavrel.eee\100tznvy\056pbz
mailto: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;%72%61%6R%69%65%72%79.%72%72%72@%67%6Q%61%69%6P.%63%6S%6Q"
description: Software Enginner
baseurl: ""
hostname: raniery.com.br
url: http://raniery.com.br
permalink: /:title/
phone: "\x2B5561984126694"
phone_mask: +55 (61) 9 8412 6694

twitter_username: ranieryribeiro
github_username: raniery
facebook_username: raniery.rrr

# Google-analytics
google-analytics:
  id: "UA-109418819-1"

# Build settings
markdown: kramdown
